'use client';

import { useTranslation } from '../../../lib/i18n-client';
import { useAttributes } from './useAttributes';
import { ValueEditForm } from './ValueEditForm';

export function AttributesPageContent() {
  const { t } = useTranslation();
  const {
    // State
    attributes,
    loading,
    showAddForm,
    editingAttribute,
    editingAttributeName,
    savingAttribute,
    expandedAttributes,
    formData,
    newValue,
    addingValueTo,
    deletingValue,
    editingValue: _editingValue,
    valueError,
    expandedValueId,
    editingLabel,
    editingColors,
    editingImageUrl,
    savingValue,
    imageUploading,
    fileInputRef,
    // Actions
    setShowAddForm,
    setFormData,
    setNewValue,
    setEditingAttributeName,
    setEditingLabel,
    setEditingColors,
    setEditingImageUrl: _setEditingImageUrl,
    setValueError,
    handleCreateAttribute,
    handleDeleteAttribute,
    handleUpdateAttributeName,
    toggleAttributeEdit,
    handleAddValue,
    handleDeleteValue,
    toggleValueEdit,
    handleImageUpload,
    handleRemoveImage,
    handleSaveInlineValue,
    toggleExpand,
  } = useAttributes();
  const totalValues = attributes.reduce((sum, attribute) => sum + attribute.values.length, 0);
  const totalValuesLabel = t('admin.attributes.valuesPlural').replace('{count}', '').trim() || 'Values';

  if (loading) {
    return (
      <div className="py-12 text-center">
        <div className="mx-auto mb-4 h-8 w-8 animate-spin rounded-full border-b-2 border-gray-900"></div>
        <p className="text-sm text-gray-600">{t('admin.attributes.loadingAttributes')}</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <section className="overflow-hidden rounded-2xl border border-gray-200/80 bg-gradient-to-br from-white via-gray-50 to-amber-50/60 p-6 shadow-[0_10px_40px_-24px_rgba(17,24,39,0.35)]">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="space-y-2">
            <p className="inline-flex items-center rounded-full border border-marco-yellow/40 bg-marco-yellow/15 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-gray-700">
              Attribute Center
            </p>
            <h2 className="text-2xl font-semibold text-gray-900">{t('admin.attributes.title')}</h2>
            <p className="max-w-2xl text-sm text-gray-600">{t('admin.attributes.subtitle')}</p>
          </div>
          <div className="grid min-w-[210px] grid-cols-2 gap-3">
            <div className="rounded-xl border border-white/80 bg-white/80 p-3 backdrop-blur-sm">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-500">{t('admin.attributes.title')}</p>
              <p className="mt-1 text-2xl font-semibold text-gray-900">{attributes.length}</p>
            </div>
            <div className="rounded-xl border border-white/80 bg-white/80 p-3 backdrop-blur-sm">
              <p className="text-xs font-medium uppercase tracking-wide text-gray-500">{totalValuesLabel}</p>
              <p className="mt-1 text-2xl font-semibold text-gray-900">{totalValues}</p>
            </div>
          </div>
        </div>
      </section>

      <div className="flex items-center justify-end">
        <button
          onClick={() => setShowAddForm(!showAddForm)}
          className="inline-flex h-10 items-center gap-2 rounded-xl bg-marco-yellow px-4 text-sm font-semibold text-marco-black shadow-sm transition-all hover:-translate-y-px hover:brightness-95"
        >
          <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
          </svg>
          {showAddForm ? t('admin.attributes.cancel') : t('admin.attributes.addAttribute')}
        </button>
      </div>

        {/* Add Attribute Form */}
        {showAddForm && (
          <div className="admin-card mb-6 border border-gray-200/80 bg-white/95 shadow-[0_12px_28px_-20px_rgba(17,24,39,0.45)]">
            <h2 className="mb-4 text-lg font-semibold text-gray-900">{t('admin.attributes.createNewAttribute')}</h2>
            <form onSubmit={handleCreateAttribute} className="space-y-4">
              <div>
                <label className="mb-1 block text-sm font-medium text-gray-700">
                  {t('admin.attributes.name')} <span className="text-red-500">{t('admin.attributes.required')}</span>
                </label>
                <input
                  type="text"
                  value={formData.name}
                  onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  placeholder={t('admin.attributes.namePlaceholder')}
                  className="admin-field"
                  required
                />
                <p className="mt-1 text-xs text-gray-500">
                  {t('admin.attributes.keyAutoGenerated')}
                </p>
              </div>

              <div className="flex gap-3 pt-2">
                <button
                  type="submit"
                  className="inline-flex h-10 items-center rounded-xl bg-marco-yellow px-4 text-sm font-semibold text-marco-black transition-colors hover:brightness-95"
                >
                  {t('admin.attributes.createAttribute')}
                </button>
                <button
                  type="button"
                  onClick={() => {
                    setShowAddForm(false);
                    setFormData({ name: '' });
                  }}
                  className="inline-flex h-10 items-center rounded-xl border border-gray-300 bg-white px-4 text-sm font-medium text-gray-700 transition-colors hover:bg-gray-100"
                >
                  {t('admin.attributes.cancel')}
                </button>
              </div>
            </form>
          </div>
        )}

        {/* Attributes List */}
        {attributes.length === 0 ? (
          <div className="admin-card border border-dashed border-gray-300/90 bg-gradient-to-b from-white to-gray-50 py-12 text-center shadow-none">
            <svg className="mx-auto mb-4 h-16 w-16 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z" />
            </svg>
            <h3 className="mb-2 text-lg font-medium text-gray-900">{t('admin.attributes.noAttributes')}</h3>
            <p className="mb-4 text-gray-600">{t('admin.attributes.getStarted')}</p>
            <button
              onClick={() => setShowAddForm(true)}
              className="inline-flex h-10 items-center rounded-xl bg-marco-yellow px-4 text-sm font-semibold text-marco-black transition-colors hover:brightness-95"
            >
              {t('admin.attributes.createAttribute')}
            </button>
          </div>
        ) : (
          <div className="space-y-3">
            {attributes.map((attribute) => {
              const isExpanded = expandedAttributes.has(attribute.id);
              return (
                <div
                  key={attribute.id}
                  className="overflow-hidden rounded-xl border border-gray-200/80 bg-white shadow-[0_10px_30px_-22px_rgba(17,24,39,0.45)] transition-shadow hover:shadow-[0_16px_34px_-20px_rgba(17,24,39,0.4)]"
                >
                  {/* Attribute Header */}
                  <div className="flex items-center justify-between p-4 transition-colors hover:bg-gray-50/70">
                    <div className="flex flex-1 items-center gap-4">
                      <button
                        onClick={() => toggleExpand(attribute.id)}
                        className="rounded-lg p-1 text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
                      >
                        <svg
                          className={`w-5 h-5 transition-transform ${isExpanded ? 'rotate-90' : ''}`}
                          fill="none"
                          stroke="currentColor"
                          viewBox="0 0 24 24"
                        >
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                        </svg>
                      </button>
                      <div className="flex-1">
                        {editingAttribute === attribute.id ? (
                          <div className="flex items-center gap-2">
                            <input
                              type="text"
                              value={editingAttributeName}
                              onChange={(e) => setEditingAttributeName(e.target.value)}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter' && editingAttributeName.trim()) {
                                  handleUpdateAttributeName(attribute.id);
                                }
                              }}
                              className="rounded-xl border border-gray-300 px-3 py-2 text-lg font-semibold focus:border-transparent focus:ring-2 focus:ring-gray-900"
                              autoFocus
                            />
                            <button
                              onClick={() => handleUpdateAttributeName(attribute.id)}
                              disabled={!editingAttributeName.trim() || savingAttribute}
                              className="flex items-center gap-2 rounded-xl bg-marco-yellow px-3 py-2 font-semibold text-marco-black transition-colors hover:brightness-95 disabled:cursor-not-allowed disabled:opacity-50"
                            >
                              {savingAttribute ? (
                                <>
                                  <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                                  {t('admin.attributes.saving') || 'Saving...'}
                                </>
                              ) : (
                                <>
                                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                                  </svg>
                                  {t('admin.attributes.save') || 'Save'}
                                </>
                              )}
                            </button>
                            <button
                              onClick={() => toggleAttributeEdit(attribute)}
                              disabled={savingAttribute}
                              className="rounded-xl bg-gray-200 px-3 py-2 text-gray-700 transition-colors hover:bg-gray-300 disabled:opacity-50"
                            >
                              {t('admin.attributes.cancel')}
                            </button>
                          </div>
                        ) : (
                          <>
                            <div className="flex items-center gap-3">
                              <h3 className="text-lg font-semibold text-gray-900">{attribute.name}</h3>
                              <span className="rounded-md bg-gray-100 px-2 py-1 text-xs text-gray-600">
                                {attribute.key}
                              </span>
                              {attribute.filterable && (
                                <span className="rounded-md border border-amber-200 bg-amber-50 px-2 py-1 text-xs font-medium text-amber-700">
                                  {t('admin.attributes.filterable')}
                                </span>
                              )}
                            </div>
                            <p className="mt-1 text-sm text-gray-500">
                              {attribute.values.length === 1 
                                ? t('admin.attributes.values').replace('{count}', attribute.values.length.toString())
                                : t('admin.attributes.valuesPlural').replace('{count}', attribute.values.length.toString())
                              }
                            </p>
                          </>
                        )}
                      </div>
                    </div>
                    {editingAttribute !== attribute.id && (
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => toggleAttributeEdit(attribute)}
                          className="rounded-lg px-3 py-2 text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-900"
                          title={t('admin.attributes.editAttribute') || 'Edit attribute'}
                        >
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </button>
                        <button
                          onClick={() => handleDeleteAttribute(attribute.id, attribute.name)}
                          className="rounded-lg px-3 py-2 text-red-600 transition-colors hover:bg-red-50 hover:text-red-800"
                          title={t('admin.attributes.deleteAttribute')}
                        >
                          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                          </svg>
                        </button>
                      </div>
                    )}
                  </div>

                  {/* Values Section */}
                  {isExpanded && (
                    <div className="border-t border-gray-200 bg-gradient-to-b from-gray-50/80 to-white p-4">
                      {/* Add Value Form */}
                      <div className="mb-5 rounded-xl border border-gray-200 bg-white p-3 shadow-[0_4px_14px_-10px_rgba(17,24,39,0.25)]">
                        <div className="flex gap-2">
                          <div className="flex-1">
                            <input
                              type="text"
                              value={newValue}
                              onChange={(e) => {
                                setNewValue(e.target.value);
                                // Clear error when user starts typing
                                if (valueError) {
                                  setValueError(null);
                                }
                              }}
                              onKeyPress={(e) => {
                                if (e.key === 'Enter' && newValue.trim()) {
                                  handleAddValue(attribute.id);
                                }
                              }}
                              placeholder={t('admin.attributes.addNewValue')}
                              className={`
                                w-full rounded-xl border px-3 py-2 transition-colors focus:border-transparent focus:ring-2
                                ${valueError 
                                  ? 'border-red-300 bg-red-50 focus:ring-red-500' 
                                  : 'border-gray-300 focus:ring-gray-900'
                                }
                              `}
                            />
                            {valueError && (
                              <p className="mt-1 text-sm text-red-600 flex items-center gap-1">
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                                {valueError}
                              </p>
                            )}
                          </div>
                          <button
                            onClick={() => handleAddValue(attribute.id)}
                            disabled={!newValue.trim() || addingValueTo === attribute.id}
                            className="flex items-center gap-2 rounded-xl bg-marco-yellow px-4 py-2 font-semibold text-marco-black transition-colors hover:brightness-95 disabled:cursor-not-allowed disabled:opacity-50"
                          >
                            {addingValueTo === attribute.id ? (
                              <>
                                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                                {t('admin.attributes.adding')}
                              </>
                            ) : (
                              <>
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                                </svg>
                                {t('admin.attributes.add')}
                              </>
                            )}
                          </button>
                        </div>
                      </div>

                      {/* Values List */}
                      {attribute.values.length === 0 ? (
                        <p className="text-sm text-gray-500 py-4 text-center">{t('admin.attributes.noValuesYet')}</p>
                      ) : (
                        <div className="space-y-2">
                          {attribute.values.map((value) => {
                            const isExpanded = expandedValueId === value.id;
                            return (
                              <div
                                key={value.id}
                                className="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-[0_8px_24px_-18px_rgba(17,24,39,0.35)]"
                              >
                                {/* Value Card */}
                                <div className="flex items-center justify-between p-3 transition-colors hover:bg-gray-50">
                                  <div className="flex flex-1 items-center gap-2">
                                    {/* Color swatch or image */}
                                    {value.colors && value.colors.length > 0 ? (
                                      <span
                                        className="inline-block h-5 w-5 flex-shrink-0 rounded-full border border-gray-300 shadow-inner"
                                        style={{ backgroundColor: value.colors[0] }}
                                        title={value.colors[0]}
                                      />
                                    ) : value.imageUrl ? (
                                      <img
                                        src={value.imageUrl}
                                        alt={value.label}
                                        className="h-5 w-5 flex-shrink-0 rounded border border-gray-300 object-cover"
                                      />
                                    ) : null}
                                    <span className="text-sm font-medium text-gray-900">{value.label}</span>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <button
                                      onClick={() => toggleValueEdit(attribute.id, value)}
                                      className="rounded-lg p-1 text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-900"
                                      title={t('admin.attributes.configureValue') || 'Configure value'}
                                    >
                                      <svg
                                        className={`w-4 h-4 transition-transform ${isExpanded ? 'rotate-90' : ''}`}
                                        fill="none"
                                        stroke="currentColor"
                                        viewBox="0 0 24 24"
                                      >
                                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                                      </svg>
                                    </button>
                                    <button
                                      onClick={() => handleDeleteValue(attribute.id, value.id, value.label)}
                                      disabled={deletingValue === value.id}
                                      className="rounded-lg p-1 text-red-600 transition-colors hover:bg-red-50 hover:text-red-800 disabled:opacity-50"
                                      title={t('admin.attributes.deleteValue')}
                                    >
                                      {deletingValue === value.id ? (
                                        <div className="w-4 h-4 border-2 border-red-600 border-t-transparent rounded-full animate-spin" />
                                      ) : (
                                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                        </svg>
                                      )}
                                    </button>
                                  </div>
                                </div>

                                {/* Inline Edit Form */}
                                {isExpanded && (
                                  <ValueEditForm
                                    attributeId={attribute.id}
                                    value={value}
                                    editingLabel={editingLabel}
                                    editingColors={editingColors}
                                    editingImageUrl={editingImageUrl}
                                    savingValue={savingValue}
                                    imageUploading={imageUploading}
                                    fileInputRef={fileInputRef}
                                    onLabelChange={setEditingLabel}
                                    onColorsChange={setEditingColors}
                                    onImageUpload={handleImageUpload}
                                    onRemoveImage={handleRemoveImage}
                                    onSave={handleSaveInlineValue}
                                    onCancel={() => toggleValueEdit(attribute.id, value)}
                                  />
                                )}
                              </div>
                            );
                          })}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
    </div>
  );
}

