'use client';

import { useEffect } from 'react';
import type { Attribute, GeneratedVariant } from '../types';
import { generateSlug } from '../utils/productUtils';
import { logger } from "@/lib/utils/logger";

interface UseVariantGenerationProps {
  selectedAttributesForVariants: Set<string>;
  selectedAttributeValueIds: Record<string, string[]>;
  attributes: Attribute[];
  generatedVariants: GeneratedVariant[];
  formDataSlug: string;
  formDataTitle: string;
  isEditMode: boolean;
  productId: string | null;
  setGeneratedVariants: (updater: (prev: GeneratedVariant[]) => GeneratedVariant[]) => void;
}

export function useVariantGeneration({
  selectedAttributesForVariants,
  selectedAttributeValueIds,
  attributes,
  generatedVariants,
  formDataSlug,
  formDataTitle,
  isEditMode,
  productId,
  setGeneratedVariants,
}: UseVariantGenerationProps) {
  const areValueIdsEqual = (left: string[], right: string[]) => {
    if (left.length !== right.length) return false;
    for (let index = 0; index < left.length; index += 1) {
      if (left[index] !== right[index]) return false;
    }
    return true;
  };

  const generateVariantsFromAttributes = () => {
    logger.devLog('🚀 [VARIANT BUILDER] Generating single variant with all attributes...');

    const selectedAttrs = Array.from(selectedAttributesForVariants);
    if (selectedAttrs.length === 0) {
      logger.devLog('⚠️ [VARIANT BUILDER] No attributes selected');
      setGeneratedVariants(() => []);
      return;
    }

    setGeneratedVariants((prev) => {
      const manuallyAddedVariants = prev.filter((v) => v.id !== 'variant-all');
      const existingAutoVariant = prev.find((v) => v.id === 'variant-all');

      if (manuallyAddedVariants.length > 0) {
        if (!existingAutoVariant && manuallyAddedVariants.length === prev.length) {
          return prev;
        }
        logger.devLog('✅ [VARIANT BUILDER] Manual variants exist, skipping auto-generated variant');
        return manuallyAddedVariants;
      }

      const variantId = 'variant-all';
      const allSelectedValueIds: string[] = [];
      selectedAttrs.forEach((attributeId) => {
        const selectedIds = selectedAttributeValueIds[attributeId] || [];
        allSelectedValueIds.push(...selectedIds);
      });
      allSelectedValueIds.sort();

      const baseSlug = formDataSlug || generateSlug(formDataTitle) || 'PROD';
      let sku = `${baseSlug}`;

      if (allSelectedValueIds.length > 0) {
        const valueParts: string[] = [];
        selectedAttrs.forEach((attributeId) => {
          const attribute = attributes.find((a) => a.id === attributeId);
          if (!attribute) return;

          const selectedIds = selectedAttributeValueIds[attributeId] || [];
          selectedIds.forEach((valueId) => {
            const value = attribute.values.find((v) => v.id === valueId);
            if (value) {
              valueParts.push(value.value.toUpperCase().replace(/\s+/g, '-'));
            }
          });
        });

        if (valueParts.length > 0) {
          sku = `${baseSlug}-${valueParts.join('-')}`;
        }
      }

      const autoVariant: GeneratedVariant = {
        id: variantId,
        selectedValueIds: allSelectedValueIds,
        price: existingAutoVariant?.price || '',
        compareAtPrice: existingAutoVariant?.compareAtPrice || '',
        stock: existingAutoVariant?.stock || '',
        sku: existingAutoVariant?.sku || sku,
        image: existingAutoVariant?.image || null,
      };

      if (
        prev.length === 1 &&
        prev[0]?.id === 'variant-all' &&
        areValueIdsEqual(prev[0].selectedValueIds, autoVariant.selectedValueIds) &&
        prev[0].price === autoVariant.price &&
        prev[0].compareAtPrice === autoVariant.compareAtPrice &&
        prev[0].stock === autoVariant.stock &&
        prev[0].sku === autoVariant.sku &&
        prev[0].image === autoVariant.image
      ) {
        return prev;
      }

      const result = [autoVariant];
      logger.devLog('✅ [VARIANT BUILDER] Variants updated:', {
        manuallyAdded: 0,
        autoGenerated: 1,
        total: result.length,
      });
      return result;
    });

    logger.devLog('✅ [VARIANT BUILDER] Single variant generated with', selectedAttrs.length, 'attributes');
  };

  const applyToAllVariants = (field: 'price' | 'compareAtPrice' | 'stock' | 'sku', value: string) => {
    setGeneratedVariants((prev) =>
      prev.map((variant) => ({
        ...variant,
        [field]: value,
      }))
    );
  };

  useEffect(() => {
    const hasPendingInitialConversion = Boolean(
      isEditMode &&
      productId &&
      (window as any).__productVariantsToConvert &&
      selectedAttributesForVariants.size === 0
    );

    // Wait only for initial conversion from existing DB variants.
    // If user already picked attributes, generate live rows immediately.
    if (hasPendingInitialConversion) {
      return;
    }

    if (selectedAttributesForVariants.size > 0) {
      generateVariantsFromAttributes();
    } else {
      if (!isEditMode) {
        setGeneratedVariants(() => []);
      }
    }
     
  }, [selectedAttributesForVariants, selectedAttributeValueIds, attributes, formDataSlug, formDataTitle, isEditMode, productId, generatedVariants]);

  return {
    generateVariantsFromAttributes,
    applyToAllVariants,
  };
}


